CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT
BEGIN
  RETURN (
    SELECT CASE WHEN ALL_RANK = N THEN SALARY ELSE NULL END AS RESULT
    FROM (SELECT DENSE_RANK() OVER (ORDER BY SALARY DESC) AS ALL_RANK, SALARY
          FROM EMPLOYEE) AS E
    ORDER BY RESULT DESC
    LIMIT 1
  );
END